# Generated by Django 5.0.6 on 2024-05-12 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_remove_lesson_course'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_day', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата оплаты')),
                ('sum_pay', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма оплаты')),
                ('pay_method', models.CharField(blank=True, max_length=100, null=True, verbose_name='Способ оплаты')),
                ('course_pay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.course', verbose_name='Оплаченный курс')),
                ('lesson_pay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.lesson', verbose_name='Оплаченный урок')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
