# Generated by Django 5.0.6 on 2024-05-19 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'ordering': ('user', 'pay_day'), 'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
    ]
