# Generated by Django 5.0.6 on 2024-05-12 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(default='Курс не указан', on_delete=django.db.models.deletion.CASCADE, to='lms.course', verbose_name='Название курса'),
        ),
    ]
