# Generated by Django 5.0.6 on 2024-05-12 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_lesson_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
    ]
